StartingGold: 150
MySQL:
    Host: 127.0.0.1
    Database: eden
    Username: root
    Password: ee7aa198e7
    TablePrefix: kingdoms
Items:
    Satchel:
        Item: GOLD_AXE
        Data: 2
        Name: Satchel
Races:
    Human:
        GUI:
            Material: IRON_CHESTPLATE
            Color: "§b"
            Lore:
            - "§b+ Luck"
        Effects:
            1:
            - "LUCK.1000000.0.false"
            2:
            - "LUCK.1000000.1.false"
    Dwarf:
        GUI:
            Material: DIAMOND_CHESTPLATE
            Color: "§e"
            Lore:
            - "§e+ Efficiency"
        Effects:
            1:
            - "FAST_DIGGING.1000000.0.false"
            2:
            - "FAST_DIGGING.1000000.1.false"
    Orc:
        GUI:
            Material: GOLD_CHESTPLATE
            Color: "§c"
            Lore:
            - "§c+ Damage"
        Effects:
            1:
            - "INCREASE_DAMAGE.1000000.0.false"
            2:
            - "INCREASE_DAMAGE.1000000.1.false"
    Elf:
        GUI:
            Material: LEATHER_CHESTPLATE
            Color: "§a"
            Lore:
            - "§a+ Speed"
        Effects:
            1:
            - "SPEED.1000000.0.false"
            2:
            - "SPEED.1000000.1.false"